import type { Metadata } from "next";
import { inter, variables } from "@/lib/fonts";
import "./globals.css";
import Page from "@/components/organisms/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={variables}>
      <body className={inter.className}>
        <Page>{children}</Page>
      </body>
    </html>
  );
}
