import type { Metadata } from "next";
import { inter, variables } from "@/lib/fonts";
import "./globals.css";
import Navigation from "@/components/molecules/navigation";
import Footer from "@/components/molecules/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={variables}>
      <body className={`${inter.className} flex flex-col min-h-screen w-full`}>
        <Navigation />
        <main className="flex flex-1 flex-col items-center">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
