import type { Metadata } from "next";
import { inter, variables } from "@/lib/fonts";
import "./globals.css";
import WithEncryption from "@/contexts/with-encryption";
import Page from "@/components/organisms/page";

export const metadata: Metadata = {
  title: "Bodypace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={variables}>
      <body className={inter.className}>
        <WithEncryption>
          <Page>{children}</Page>
        </WithEncryption>
      </body>
    </html>
  );
}
