import Document, {
  DocumentPart,
  DocumentPartType,
} from "@/components/atoms/document";

//prettier-ignore
const document: DocumentPart[] = [
  [ DocumentPartType.Paragraph, "Last updated on: 2024-04-27" ],
  [ DocumentPartType.Title, "Terms and Conditions for website" ],
  [ DocumentPartType.Paragraph, 'Welcome to bodypace.org (the "Website"). These Terms and Conditions govern your use of the Website. By accessing or using the Website, you agree to be bound by these Terms and Conditions.' ],
  [ DocumentPartType.Header, "1. User Registration" ],
  [ DocumentPartType.Paragraph, "1.1. Users may register for an account on bodypace.org through bodypace.org website or by making requests to public API at api.bodypace.org. Registration is open to individuals except children under the age of 13 or individuals for whom providing an account may violate applicable laws." ],
  [ DocumentPartType.Header, "2. User Responsibilities" ],
  [ DocumentPartType.Paragraph, "2.1. Users are responsible for ensuring that files uploaded to bodypace.org are encrypted on their side (client-side) before transmission, especially when using the API. While we make efforts to ensure files uploaded via our website interface are encrypted in the browser, users are ultimately responsible for verification." ],
  [ DocumentPartType.Paragraph, "2.2. Users are responsible for securely storing their personal encryption keys generated by bodypace.org or manually." ],
  [ DocumentPartType.Paragraph, "2.3. Users must not disclose their username and password to others." ],
  [ DocumentPartType.Paragraph, '2.4. The Website is provided "as is" without warranty. The source code is open and free to audit.' ],
  [ DocumentPartType.Header, "3. Data Handling and Privacy" ],
  [ DocumentPartType.Paragraph, "3.1. Users' data handling and privacy are governed by the Privacy Policy available on the Website." ],
  [ DocumentPartType.Header, "4. Intellectual Property Rights" ],
  [ DocumentPartType.Paragraph, "4.1. bodypace.org does not claim ownership or licensing rights over user-generated content. Users must only upload encrypted end-to-end data to the Website." ],
  [ DocumentPartType.Header, "5. Prohibited Activities" ],
  [ DocumentPartType.Paragraph, "5.1. Uploading unencrypted data is prohibited. bodypace.org reserves the right to modify or delete unencrypted user data." ],
  [ DocumentPartType.Header, "6. Termination of Accounts" ],
  [ DocumentPartType.Paragraph, "6.1. bodypace.org may delete user data and terminate accounts at any time without notice, as the Website is currently in a free beta version with no guaranteed data retention." ],
  [ DocumentPartType.Header, "7. Limitation of Liability" ],
  [ DocumentPartType.Paragraph, '7.1. bodypace.org provides the Website "as is" without warranty. We do not guarantee accessibility, functionality, or uptime. We are not liable for any failures to provide our services.' ],
  [ DocumentPartType.Paragraph, "7.2. bodypace.org is only liable for data uploaded correctly encrypted by users, but retains the right to modify or remove such data at any time." ],
  [ DocumentPartType.Header, "8. Governing Law" ],
  [ DocumentPartType.Paragraph, "8.1. These Terms and Conditions are governed by local law. Users are responsible for compliance with applicable laws in their jurisdiction." ],
  [ DocumentPartType.Header, "9. Updates and Amendments" ],
  [ DocumentPartType.Paragraph, "9.1. Users are required to check the Website for updates to the Terms and Conditions and Privacy Policy. Continued usage of the Website constitutes acceptance of the current Terms and Conditions and Privacy Policy." ],
  [ DocumentPartType.Header, "10. Contact Us" ],
  [ DocumentPartType.Paragraph, "10.1 If you have any questions or concerns about these Terms and Conditions, please contact us at contact@bodypace.org." ],
  [ DocumentPartType.Paragraph, "Thank you for using bodypace.org!" ],
]

export default function TermsAndConditionsPage() {
  return <Document document={document} />;
}
